# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gq < Formula
  desc "jq like cli written in go"
  homepage ""
  version "1.6.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jmpargana/gq/releases/download/v1.6.3/gq_Darwin_x86_64.tar.gz"
      sha256 "6786862e59ef551c525548ea19686749126203269ec6952f82516415a9450d76"

      def install
        bin.install Dir["*/gq"]
        man1.install "gq.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jmpargana/gq/releases/download/v1.6.3/gq_Darwin_arm64.tar.gz"
      sha256 "689cb87a8d39ad8bd058892afae4856553a0b4dff3091a057f16293b0fa37806"

      def install
        bin.install Dir["*/gq"]
        man1.install "gq.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmpargana/gq/releases/download/v1.6.3/gq_Linux_x86_64.tar.gz"
      sha256 "15620b13ffd1b14456d94a739455545949b35278be2cb53c422c8a0acf2da906"
      def install
        bin.install Dir["*/gq"]
        man1.install "gq.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmpargana/gq/releases/download/v1.6.3/gq_Linux_arm64.tar.gz"
      sha256 "a8489d450c95720475b2c3234adceac8cf6019d908058bdadb8b8abcae841137"
      def install
        bin.install Dir["*/gq"]
        man1.install "gq.1"
      end
    end
  end

  test do
    system "#{bin}/gq --version"
  end
end
